OOP school library: refactor your code 🟢
haliljon/OOP-school-library pull request #5
Opened 2023-03-20 14:59 UTC by SabaAhmad404

in this project we are the team of three people

1. @tobuya 
2. @haliljon 
3. @SabaAhmad404 

- we work to refactor the main.rb file, 

- our code is YAGNI, KISS, DRY,

- we Solid principles

- we added the ruby linters

kindly review our code

2023-03-20 15:48 UTC, rloterh requested changes
Hi Team, 

You did extremely great on this project! 👏 👏 
There are however a few issues that you still need to work on to go to the next project but you are almost there!  

## Highlights 👍  
- Good job so far working on clean code principles!
- ReadMe looks good!

## Required Changes ♻️
- [ ] Good job so far, however, we can further improve upon our _create_ and _list all_ methods found in the `app.rb`, which at present do not adhere to the single responsibility rule. Let's ensure that the create or list methods simply creates or list associated objects, and other logics or functionalities such as requests for input (`get.chomps`) or input validations are placed in a separate classes, methods, or in the the `main.rb`. The affected methods to consider for further refactoring includes:
  * `create_person` 
  * `create_student`
  * `craete_teacher`
  * `create_book`,
  * `create_rental` and
  * `list_all_rentals_for_person_id` 

The example below are methods that have focused responsibility:
```ruby
class App
  
  . . .
  
  def list_books
    @books.each do |book|
      puts book
    end
  end

  def list_people
    @people.each do |person|
      puts person
    end

  . . .

end
```

I urge you to kindly read further on the same via [this link](https://github.com/microverseinc/curriculum-ruby/blob/main/oop/lessons/solid.md#best-practices-and-solid).

Cheers and Happy coding!👏 💻 🍷

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561) you have a limited number of reviews per project (check the exact number in your Dashboard). If you think the code review was unfair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 09:07 UTC, Olamarx requested changes
Hi Team, 

Great work on making the changes requested by a previous reviewer 👏 
You've done well implementing some of the requested changes, but there are still some which aren't addressed yet.
<img src="https://media4.giphy.com/media/xUOxfh6ZM75efM3Bqo/giphy-downsized-medium.gif"/>

 ## Highlights
- Linters passed ✔️
- Professional Readme file ✔️ 

 ## Required Changes ♻️
_Check the comments under the review._
- [ ] The create_rental appears merged, kindly take note it is also part.

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._


Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

**_Please, do not open a new Pull Request for re-reviews. You should use the same Pull Request submitted for the first review, either valid or invalid unless it is requested otherwise._**


------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 09:07 UTC, Olamarx commented on app.rb
> +    input = get_user_input_int('Do you want to create a student (1) or a teacher (2)? [Input the number]:')
- [ ] Just as the previous reviewer recommended, I will implore you to extract every function related to creating new data or listing existing data, in another file and it can be in the main.rb. This is the essence of the single responsibility rule so that each file will have a general and related responsibility.

2023-03-21 09:07 UTC, Olamarx commented on app.rb
> +    has_permission = get_user_input_string('Has parent permission? [Y/N]:').upcase
- [ ]  Just as the previous reviewer recommended, I will implore you to extract every function related to creating new data or listing existing data, in another file and it can be in the main.rb. This is the essence of the single responsibility rule so that each file will have a general and related responsibility.

2023-03-21 09:07 UTC, Olamarx commented on app.rb
> +    @people << Teacher.new(specialization, age, name)
- [ ]  Just as the previous reviewer recommended, I will implore you to extract every function related to creating new data or listing existing data, in another file and it can be in the main.rb. This is the essence of the single responsibility rule so that each file will have a general and related responsibility.

2023-03-21 09:07 UTC, Olamarx commented on app.rb
> +    author = get_user_input_string('Author:')
- [ ]  Just as the previous reviewer recommended, I will implore you to extract every function related to creating new data or listing existing data, in another file and it can be in the main.rb. This is the essence of the single responsibility rule so that each file will have a general and related responsibility.

2023-03-21 13:59 UTC, PinkMoon25 approved these changes
Hi @SabaAhmad404 , @tobuya & @haliljon , 

Your project is complete!  There is nothing else to say other than... it's time to merge it :shipit: 
Congratulations! 🎉 

## Highlights
Linters :heavy_check_mark: 
Gitflow :heavy_check_mark: 
Refactor :heavy_check_mark: 
Professional Readme :heavy_check_mark: 

## Optional suggestions

_Every comment with the [OPTIONAL] prefix won't stop the approval of this PR. However, I strongly recommend you to take them into account as they can make your code better. Some of them were simply missed by the previous reviewer and addressing them will really improve your application._

Cheers and Happy coding!👏👏👏

Feel free to leave any questions or comments in the PR thread if something is not 100% clear.
Please, remember to tag me in your question so I can receive the notification.

------
_As described in the [Code reviews limits policy](https://microverse.zendesk.com/hc/en-us/articles/1500004088561)  you have a limited number of reviews per project (check the exact number in your Dashboard). If you think that the code review was not fair, you can request a second opinion using [this form](https://airtable.com/shrQAqnBwek5a0O0s)._

2023-03-21 14:34 UTC, merged